[[groups]]
  name = "Dotfiles"
[[groups.items]]
  type = "symlink"
  paths = [
    ".editorconfig",
    ".hushlogin",
    ".zprofile",
    ".zshrc",
  ]

[[groups]]
  name = "Oh My Zsh"
[[groups.items]]
  type = "symlink"
  paths = [
    [".oh-my-zsh", { type = "dir" }],
  ]

[[groups]]
  name = "Git"
[[groups.items]]
  type = "symlink"
  paths = [
    ".gitattributes_global",
    ".gitconfig",
    ".gitignore_global",
  ]

[[groups]]
  name = "Atuin"
[[groups.items]]
  type = "symlink"
  paths = [
    [".config/atuin", { type = "dir" }],
  ]

[[groups]]
  name = "tmux"
[[groups.items]]
  type = "symlink"
  paths = [
    ".tmux.conf",
    [".tmux", { type = "dir" }],
  ]

[[groups]]
  name = "lazygit"
[[groups.items]]
  type  = "symlink"
  paths = ["Library/Application Support/lazygit/config.yml"]

[[groups]]
  name = "powerlevel10k"
[[groups.items]]
  type  = "symlink"
  paths = [".p10k.zsh"]

[[groups]]
  name = "iTerm"
[[groups.items]]
  type = "defaults"
  domains = [
    [
      "com.googlecode.iterm2",
      { include = [
        "/AdjustWindowForFontSizeChange",
        "/AlternateMouseScroll",
        "/BadgeFont",
        "/Custom Color Presets",
        "/Default Bookmark Guid",
        "/DimBackgroundWindows",
        "/DimOnlyText",
        "/DisableWindowSizeSnap",
        "/EnableAPIServer",
        "/HapticFeedbackForEsc",
        "/HideTab",
        "/HotkeyMigratedFromSingleToMulti",
        "/IRMemory",
        "/New Bookmarks",
        "/PointerActions",
        "/SeparateStatusBarsPerPane",
        "/SoundForEsc",
        "/SplitPaneDimmingAmount",
        "/SwitchPaneModifier",
        "/TabStyleWithAutomaticOption",
        "/UseBorder",
        "/VisualIndicatorForEsc",
        "/findMode_iTerm",
        "/kCPKSelectionViewPreferredModeKey",
        "/kCPKSelectionViewShowHSBTextFieldsKey",
      ] },
    ],
  ]

[[groups]]
  name = "Macs Fan Control"
[[groups.items]]
  type = "defaults"
  domains = [
    [
      "com.crystalidea.MacsFanControl",
      { exclude = [
        "/License",
        "/NSStatusItem Preferred Position MacsFanControlMenuBarIcon",
        "/UpdateChecker_NextCheck",
        "/UpdateChecker_SkipVersion",
        "/WindowGeometry",
        "/WindowSplitterPosition",
        "/WindowState",
      ] },
    ],
  ]

[[groups]]
  name = "Rectangle"
[[groups.items]]
  type = "defaults"
  domains = [
    [
      "com.knollsoft.Rectangle",
      { exclude = [
        "/NSWindow Frame SUUpdateAlert",
        "/NSWindow Frame SUUpdateAlertSmall",
        "/SULastCheckTime",
        "/SUSkippedVersion",
        "/SUUpdateGroupIdentifier",
        "/lastVersion",
      ] },
    ],
  ]


[[groups]]
  name = "AltTab"
[[groups.items]]
  type = "defaults"
  domains = [
    [
      "com.lwouis.alt-tab-macos",
      { exclude = [
        "/MSAppCenter310AppCenterUserDefaultsMigratedKey",
        "/MSAppCenter310CrashesUserDefaultsMigratedKey",
        "/MSAppCenterInstallId",
        "/MSAppCenterPastDevices",
        "/MSAppCenterNetworkRequestsAllowed",
        "/MSAppCenterSessionIdHistory",
        "/MSAppCenterUserIdHistory",
        "/NSStatusItem Visible Item-0",
        "/NSWindow Frame NSFontPanel",
        "/NSWindow Frame SUAutomaticUpdateAlert",
        "/NSWindow Frame SUStatusFrame",
        "/NSWindow Frame SUUpdateAlert",
        "/SULastCheckTime",
        "/SUUpdateGroupIdentifier",
      ] },
    ],
  ]


[[groups]]
  name = "CleanMyMac"
[[groups.items]]
  type = "defaults"
  domains = [
    [
      "com.macpaw.CleanMyMac4",
      { include = [
        "/MenubarAppEnabled",
        "/SUAutomaticallyUpdate",
        "/SUEnableAutomaticChecks",
        "/SUHasLaunchedBefore",
        "/SeenIntroVideo",
        "/ShowReleaseNotes",
        "/SmartScanModuleDisabledTasks",
      ] },
    ],
  ]
