[[groups]]
  name = "Dotfiles"
[[groups.items]]
  type = "symlink"
  paths = [
    ".editorconfig",
    ".hushlogin",
    ".zprofile",
    ".zshrc",
  ]

[[groups]]
  name = "GPG"
[[groups.items]]
  type = "symlink"
  paths = [
    ".gnupg/gpg-agent.conf",
  ]

[[groups]]
  name = "Oh My Zsh"
[[groups.items]]
  type = "symlink"
  paths = [
    [".oh-my-zsh", { type = "dir" }],
  ]

[[groups]]
  name = "LunarVim"
[[groups.items]]
  type = "symlink"
  paths = [
    [".config/lvim", { type = "dir" }],
  ]

[[groups]]
  name = "Git"
[[groups.items]]
  type = "symlink"
  paths = [
    ".gitattributes_global",
    ".gitconfig",
    ".gitignore_global",
  ]

[[groups]]
  name = "Atuin"
[[groups.items]]
  type = "symlink"
  paths = [
    [".config/atuin", { type = "dir" }],
  ]

[[groups]]
  name = "Zellij"
[[groups.items]]
  type = "symlink"
  paths = [
    [".config/zellij", { type = "dir" }],
  ]

[[groups]]
  name = "lazygit"
[[groups.items]]
  type  = "symlink"
  paths = ["Library/Application Support/lazygit/config.yml"]

[[groups]]
  name = "powerlevel10k"
[[groups.items]]
  type  = "symlink"
  paths = [".p10k.zsh"]

[[groups]]
  name = "Ghostty"
[[groups.items]]
  type = "symlink"
  paths = [
    [".config/ghostty", { type = "dir" }],
  ]

[[groups]]
  name = "MacOS"
[[groups.items]]
  type = "defaults"
  domains = [
    [
      "com.apple.dock",
      { exclude = [
        "/last-analytics-stamp",
        "/lastShowIndicatorTime",
        "/loc",
        "/mod-count",
        "/recent-apps",
        "/region",
        "/trash-full",
        "/persistent-apps/*((/{GUID|tile-type}),(/tile-data/{book|bundle-identifier|dock-extra|file-label|file-mod-date|file-type|is-beta|parent-mod-date}))",
        "/persistent-others",
      ] },
    ],
    [
      "com.apple.ActivityMonitor",
      { exclude = [
        "/Column Width",
        "/DisplayType",
        "/SelectedTab",
        "/{NSWindow Frame .*}",
        "/{NSTableView (Columns v3|Sort Ordering v2|Supports v2) cacheTableColumns}",
      ] },
    ],
    [
      "com.apple.TextEdit",
      { exclude = [
        "/NSNavPanelExpandedSizeForOpenMode",
        "/{NSWindow Frame .*}",
      ] },
    ],
    [
      "com.apple.DiskUtility",
      { exclude = [
        "/NSSplitView Subview Frames SUMainWindow",
        "/NSToolbar Configuration kMainToolbarIdentifier",
        "/{NSWindow Frame .*}",
      ] },
    ],
    [
      "com.apple.QuickTimePlayerX",
      { exclude = [
        "/MGInspectorWindowControllerShowWindowAtLaunch",
        "/MGInspectorWindowControllerWindowTopLeftPoint",
        "/MGRecentDocumentsSharedFileListIsValid",
        "/MGRecentDocumentURLBookmarks",
        "/NSNavLastUserSetHideExtensionButtonState",
        "/NSNavPanelExpandedSizeForOpenMode",
        "/NSNavPanelExpandedSizeForSaveMode",
        "/NSOSPLastRootDirectory",
        "/{NSWindow Frame .*}",
      ] },
    ],
    [
      "com.apple.screencapture",
      { exclude = [
        "/last-analytics-stamp",
        "/last-selection",
        "/last-selection-display",
        "/style",
        "/video",
      ] },
    ],
    [
      "com.apple.desktopservices",
    ],
    [
      "com.apple.frameworks.diskimages",
    ],
    [
      "com.apple.NetworkBrowser",
    ],
    [
      "com.apple.TimeMachine",
    ],
    [
      "com.apple.helpviewer",
      { exclude = [
        "/\"NSSplitView Subview Frames Tips, SidebarNavigationSplitView\"",
        "/NSWindow Frame Tips",
        "/TPSAnalyticsStore",
        "/TPSDisplayedFeaturedTopics",
        "/TPSLastFeaturedTopicsUpdateDate",
      ] },
    ],
    [
      "com.apple.systempreferences",
      { exclude = [
        "/ThirdPartyCount",
      ] },
    ],
    [
      "com.apple.print.PrintingPrefs",
    ],
    [
      "com.apple.LaunchServices",
    ],
    [
      "com.apple.appstore",
      { exclude = [
        "/ASAcknowledgedOnboardingItems",
        "/ASAcknowledgedOnboardingVersion",
        "/JetEngine_metricsSampling_page_render_sampleWindowStart",
        "/kAOSUIProfilePictureCropRect",
        "/lastBootstrapDate",
        "/lastBootstrapTimeZone",
        "/mostRecentTabIdentifier",
        "/NSWindow Frame AppStoreMainWindow",
        "/UserSetAutoPlayVideoSetting",
      ] },
    ],
    [
      "com.apple.driver.AppleBluetoothMultitouch.trackpad",
      { exclude = [
        "/UserPreferences",
        "/version",
      ] },
    ],
    [
      "com.apple.AppleMultitouchTrackpad",
      { exclude = [
        "/UserPreferences",
        "/version",
      ] },
    ],
    [
      "com.apple.HIToolbox",
      { exclude = [
        "/{Apple(CurrentKeyboardLayoutInputSourceID|EnabledInputSources|InputSourceHistory|InputSourceUpdateTime|SelectedInputSources)}",
      ] },
    ],
    "com.apple.messageshelper.MessageController",
    [
      "NSGlobalDomain",
      { include = [
        "/com.apple.mouse.tapBehavior",
      ] },
    ],
  ]

[[groups]]
  name = "iTerm"
[[groups.items]]
  type = "defaults"
  domains = [
    [
      "com.googlecode.iterm2",
      { exclude = [
        "/Default Arrangement Name",
        "/Default Bookmark Guid",
        "/{NS.*}",
        "PMPrintingPanelSize",
        "/{SU(FeedAlternateAppNameKey|FeedURL|LastCheckTime|UpdateGroupIdentifier)}",
        "/Window Arrangements",
        "/{NoSync.*}",
        "/iTerm Version",
      ] },
    ],
  ]

[[groups]]
  name = "Rectangle"
[[groups.items]]
  type = "defaults"
  domains = [
    [
      "com.knollsoft.Rectangle",
      { exclude = [
        "/{NSWindow Frame (SUUpdateAlert|SUUpdateAlertSmall)}",
        "/{SU(LastCheckTime|SkippedVersion|UpdateGroupIdentifier)}",
        "/lastVersion",
      ] },
    ],
  ]

[[groups]]
  name = "InstantSpaceSwitcher"
[[groups.items]]
  type = "defaults"
  domains = [
    [
      "com.interversehq.InstantSpaceSwitcher",
    ],
  ]


[[groups]]
  name = "AltTab"
[[groups.items]]
  type = "defaults"
  domains = [
    [
      "com.lwouis.alt-tab-macos",
      { exclude = [
        "NSOSPLastRootDirectory",
        "/{MSAppCenter.*}",
        "/NSStatusItem Visible Item-0",
        "NSNavPanelExpandedSizeForOpenMode",
        "secureData",
        "/{NSWindow Frame (NSFontPanel|SUAutomaticUpdateAlert|SUStatusFrame|SUUpdateAlert|NSNavPanelAutosaveName|PermissionsWindow|SettingsWindow)}",
        "/{SU(LastCheckTime|UpdateGroupIdentifier)}",
      ] },
    ],
  ]
