[[groups]]
  name = "Dotfiles"
[[groups.items]]
  type = "symlink"
  paths = [
    ".editorconfig",
    ".hushlogin",
    ".zprofile",
    ".zshrc",
  ]

[[groups]]
  name = "Oh My Zsh"
[[groups.items]]
  type = "symlink"
  paths = [
    [".oh-my-zsh", { type = "dir" }],
  ]

[[groups]]
  name = "Git"
[[groups.items]]
  type = "symlink"
  paths = [
    ".gitattributes_global",
    ".gitconfig",
    ".gitignore_global",
  ]

[[groups]]
  name = "Atuin"
[[groups.items]]
  type = "symlink"
  paths = [
    [".config/atuin", { type = "dir" }],
  ]

[[groups]]
  name = "tmux"
[[groups.items]]
  type = "symlink"
  paths = [
    ".tmux.conf",
    [".tmux", { type = "dir" }],
  ]

[[groups]]
  name = "lazygit"
[[groups.items]]
  type  = "symlink"
  paths = ["Library/Application Support/lazygit/config.yml"]

# TODO: delete
[[groups]]
  name = "Starship"
[[groups.items]]
  type  = "symlink"
  paths = [".config/starship.toml"]

[[groups]]
  name = "powerlevel10k"
[[groups.items]]
  type  = "symlink"
  paths = [".p10k.zsh"]

[[groups]]
  name = "iTerm"
[[groups.items]]
  type = "defaults"
  domains = [
    [
      "com.googlecode.iterm2",
      { include = [
        "/AdjustWindowForFontSizeChange",
        "/AlternateMouseScroll",
        "/BadgeFont",
        "/Custom Color Presets",
        "/Default Bookmark Guid",
        "/DimBackgroundWindows",
        "/DimOnlyText",
        "/DisableWindowSizeSnap",
        "/EnableAPIServer",
        "/HapticFeedbackForEsc",
        "/HideTab",
        "/HotkeyMigratedFromSingleToMulti",
        "/IRMemory",
        "/New Bookmarks",
        "/PointerActions",
        "/SeparateStatusBarsPerPane",
        "/SoundForEsc",
        "/SplitPaneDimmingAmount",
        "/SwitchPaneModifier",
        "/TabStyleWithAutomaticOption",
        "/UseBorder",
        "/VisualIndicatorForEsc",
        "/findMode_iTerm",
        "/kCPKSelectionViewPreferredModeKey",
        "/kCPKSelectionViewShowHSBTextFieldsKey",
      ] },
    ],
  ]

[[groups]]
  name = "Macs Fan Control"
[[groups.items]]
  type = "defaults"
  domains = [
    [
      "com.crystalidea.MacsFanControl",
      { include = [
        "/ActivePreset",
        "/AppFirstRun",
        "/CustomPresets",
        "/DontCheckForHelperTool",
        "/Fahrenheit",
        "/InterfaceLanguage",
        "/MoveToAppsSkip",
        "/PreciseTemperature",
        "/RateOnMacupdateNextDate",
        "/RateOnMacupdateSkip",
        "/ShowEGpuTemp",
        "/ShowNVMeDrives",
        "/ShowSmartDrives",
        "/UpdateChecker_Auto",
        "/menubarIcon",
        "/menubarTwoLines",
        "/trayFan",
        "/traySensor",
      ] },
    ],
  ]

[[groups]]
  name = "Rectangle"
[[groups.items]]
  type = "defaults"
  domains = [
    [
      "com.knollsoft.Rectangle",
      { include = [
        "/SUAutomaticallyUpdate",
        "/SUEnableAutomaticChecks",
        "/SUHasLaunchedBefore",
        "/alternateDefaultShortcuts",
        "/hideMenubarIcon",
        "/launchOnLogin",
        "/moveCursorAcrossDisplays",
        "/subsequentExecutionMode",
      ] },
    ],
  ]


[[groups]]
  name = "AltTab"
[[groups.items]]
  type = "defaults"
  domains = [
    [
      "com.lwouis.alt-tab-macos",
      { include = [
        "/SUAutomaticallyUpdate",
        "/SUEnableAutomaticChecks",
        "/SUHasLaunchedBefore",
        "/SUUpdateRelaunchingMarker",
        "/alignThumbnails",
        "/appsToShow",
        "/appsToShow2",
        "/crashPolicy",
        "/fadeOutAnimation",
        "/hideAppBadges",
        "/hideWindowlessApps",
        "/holdShortcut",
        "/holdShortcut2",
        "/menubarIcon",
        "/mouseHoverEnabled",
        "/nextWindowShortcut",
        "/nextWindowShortcut2",
        "/preferencesVersion",
        "/screensToShow",
        "/screensToShow2",
        "/shortcutStyle",
        "/showFullscreenWindows",
        "/showHiddenWindows",
        "/showMinimizedWindows",
        "/showOnScreen",
        "/showTabsAsWindows",
        "/spacesToShow",
        "/startAtLogin",
        "/theme",
        "/titleTruncation",
        "/updatePolicy",
        "/windowMaxWidthInRow",
      ] },
    ],
  ]


[[groups]]
  name = "CleanMyMac"
[[groups.items]]
  type = "defaults"
  domains = [
    [
      "com.macpaw.CleanMyMac4",
      { include = [
        "/MenubarAppEnabled",
        "/SUAutomaticallyUpdate",
        "/SUEnableAutomaticChecks",
        "/SUHasLaunchedBefore",
        "/SeenIntroVideo",
        "/ShowReleaseNotes",
        "/SmartScanModuleDisabledTasks",
      ] },
    ],
  ]
