[[groups]]
  name = "Dotfiles"
[[groups.items]]
  type = "symlink"
  paths = [
    ".editorconfig",
    ".hushlogin",
    ".zprofile",
    ".zshrc",
  ]

[[groups]]
  name = "Oh My Zsh"
[[groups.items]]
  type = "symlink"
  paths = [
    [".oh-my-zsh", { type = "dir" }],
  ]

[[groups]]
  name = "LunarVim"
[[groups.items]]
  type = "symlink"
  paths = [
    [".config/lvim", { type = "dir" }],
  ]

[[groups]]
  name = "Git"
[[groups.items]]
  type = "symlink"
  paths = [
    ".gitattributes_global",
    ".gitconfig",
    ".gitignore_global",
  ]

[[groups]]
  name = "Atuin"
[[groups.items]]
  type = "symlink"
  paths = [
    [".config/atuin", { type = "dir" }],
  ]

[[groups]]
  name = "Zellij"
[[groups.items]]
  type = "symlink"
  paths = [
    [".config/zellij", { type = "dir" }],
  ]

[[groups]]
  name = "lazygit"
[[groups.items]]
  type  = "symlink"
  paths = ["Library/Application Support/lazygit/config.yml"]

[[groups]]
  name = "powerlevel10k"
[[groups.items]]
  type  = "symlink"
  paths = [".p10k.zsh"]

[[groups]]
  name = "iTerm"
[[groups.items]]
  type = "defaults"
  domains = [
    [
      "com.googlecode.iterm2",
      { exclude = [
        "/Default Arrangement Name",
        "/Default Bookmark Guid",
        "/{NS.*}",
        "/{SU(FeedAlternateAppNameKey|FeedURL|LastCheckTime|UpdateGroupIdentifier)}",
        "/Window Arrangements",
        "/{NoSync.*}",
        "/iTerm Version",
      ] },
    ],
  ]

[[groups]]
  name = "Macs Fan Control"
[[groups.items]]
  type = "defaults"
  domains = [
    [
      "com.crystalidea.MacsFanControl",
      { exclude = [
        "/License",
        "/NSStatusItem Preferred Position MacsFanControlMenuBarIcon",
        "/{UpdateChecker_(NextCheck|SkipVersion)}",
        "/{Window(Geometry|SplitterPosition|State)}",
      ] },
    ],
  ]

[[groups]]
  name = "Rectangle"
[[groups.items]]
  type = "defaults"
  domains = [
    [
      "com.knollsoft.Rectangle",
      { exclude = [
        "/{NSWindow Frame (SUUpdateAlert|SUUpdateAlertSmall)}",
        "/{SU(LastCheckTime|SkippedVersion|UpdateGroupIdentifier)}",
        "/lastVersion",
      ] },
    ],
  ]


[[groups]]
  name = "AltTab"
[[groups.items]]
  type = "defaults"
  domains = [
    [
      "com.lwouis.alt-tab-macos",
      { exclude = [
        "/{MSAppCenter.*}",
        "/NSStatusItem Visible Item-0",
        "/{NSWindow Frame (NSFontPanel|SUAutomaticUpdateAlert|SUStatusFrame|SUUpdateAlert)}",
        "/{SU(LastCheckTime|UpdateGroupIdentifier)}",
      ] },
    ],
  ]


[[groups]]
  name = "CleanMyMac"
[[groups.items]]
  type = "defaults"
  domains = [
    [
      "com.macpaw.CleanMyMac4",
      { include = [
        "/MenubarAppEnabled",
        "/{SU(AutomaticallyUpdate|EnableAutomaticChecks|HasLaunchedBefore)}",
        "/SeenIntroVideo",
        "/ShowReleaseNotes",
        "/SmartScanModuleDisabledTasks",
      ] },
    ],
  ]
