"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

[directory]
    disabled          = false
    truncation_length = 15
    truncate_to_repo  = false
    truncation_symbol = "…/"

[bun]
    format = '\[[$symbol($version)]($style)\]'

[cmd_duration]
    format = '\[[⏱ $duration]($style)\]'

[dart]
    format = '\[[$symbol($version)]($style)\]'

[docker_context]
    format = '\[[$symbol$context]($style)\]'

[git_commit]
    tag_disabled = false

[git_branch]
    format = '\[[$symbol$branch]($style)\]'
    style  = "bold blue"

[git_status]
    format     = '([\[$all_status$ahead_behind\]]($style))'
    style      = "white"
    conflicted = '[✖$count](red)'
    ahead      = '[↑$count](green)'
    behind     = '[↓$count](red)'
    diverged   = "[⇕$ahead_count↓$behind_count](red)"
    up_to_date = ''
    untracked  = '[…$count](yellow)'
    stashed    = "[⚑$count](blue)"
    modified   = "[✚$count](green)"
    staged     = "[●$count](cyan)"
    renamed    = "[»$count](green)"
    deleted    = "[✖$count](red)"

[git_metrics]
    disabled = false
    format   = '([+$added]($added_style))([-$deleted]($deleted_style))'

[golang]
    format = '\[[$symbol($version)]($style)\]'

[gradle]
    format = '\[[$symbol($version)]($style)\]'

[java]
    format = '\[[$symbol($version)]($style)\]'

[kotlin]
    format = '\[[$symbol($version)]($style)\]'

[kubernetes]
    format = '\[[$symbol$context( \($namespace\))]($style)\]'

[memory_usage]
    format = '\[$symbol[$ram( | $swap)]($style)\]'

[nodejs]
    format = '\[[$symbol($version)]($style)\]'

[openstack]
    format = '\[[$symbol$cloud(\($project\))]($style)\]'

[os]
    format = '\[[$symbol]($style)\]'

[package]
    format = '\[[$symbol$version]($style)\]'

[pulumi]
    format = '\[[$symbol$stack]($style)\]'

[python]
    format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'

[ruby]
    format = '\[[$symbol($version)]($style)\]'

[rust]
    format = '\[[$symbol($version)]($style)\]'

[sudo]
    format = '\[[as $symbol]($style)\]'

[swift]
    format = '\[[$symbol($version)]($style)\]'

[time]
    format = '\[[$time]($style)\]'

[username]
    format = '\[[$user]($style)\]'

[zig]
    format = '\[[$symbol($version)]($style)\]'
