# Upstream reference:
# https://docs.atuin.sh/18.18/configuration/config/ at the time, or https://docs.atuin.sh/latest/configuration/config/

workspaces   = true
search_mode  = "fulltext"
filter_mode  = "workspace"
style        = "compact"
enter_accept = false

[search]
    filters = ["workspace", "directory", "global", "host", "session"]
