tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"

###############################################################################
# Fonts                                                                       #
###############################################################################

cask "font-jetbrains-mono-nerd-font"

###############################################################################
# Utils                                                                       #
###############################################################################

# Install GNU core utilities (those that come with macOS are outdated).
# Don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
brew 'coreutils'
# Install some other useful utilities like `sponge`.
brew 'moreutils'
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed.
brew 'findutils'
# Install GNU `sed`, overwriting the built-in `sed`.
brew 'gnu-sed'
# Install a modern version of Zsh & Bash.
brew 'zsh'
brew 'bash'

brew 'tmux'

# Install GnuPG to enable PGP-signing commits.
brew 'gnupg'

# Install more recent versions of some macOS tools.
brew 'vim'
brew 'grep'
brew 'openssh'
brew 'gmp'

# Install other useful binaries.
brew 'atuin'
brew 'bat'
brew 'eza'
brew 'fd'
brew 'fzf'
brew 'ripgrep'
brew 'gs'
brew 'imagemagick'
brew 'less'
brew 'nano'
brew 'postgresql'
brew 'rename'
brew 'shellcheck'
brew 'tldr'
brew 'tree'
brew 'watch'

###############################################################################
# Java                                                                        #
###############################################################################

brew 'maven'

###############################################################################
# Git                                                                         #
###############################################################################

brew 'git'
brew 'lazygit'
brew 'git-delta'
brew 'gh'
brew 'git-interactive-rebase-tool'

###############################################################################
# Development                                                                 #
###############################################################################

cask 'iterm2'
cask 'visual-studio-code'
cask 'jetbrains-toolbox'
cask 'docker'

###############################################################################
# Tools                                                                       #
###############################################################################

cask 'brave-browser'
cask 'alt-tab'
cask 'rectangle'
cask 'cleanmymac'
cask 'amazon-q'
cask 'raycast'
cask 'macs-fan-control'

###############################################################################
# Editing                                                                     #
###############################################################################

cask 'libreoffice'
cask 'adobe-acrobat-reader'
cask 'gimp'

###############################################################################
# Quicklook                                                                   #
###############################################################################

cask 'qlcolorcode'
cask 'qlimagesize'
cask 'qlmarkdown'
cask 'qlstephen'
cask 'qlvideo'
cask 'quicklook-json'
